fix: use proper variable for title
oat-sa/extension-lti-test-review pull request #115
Opened 2022-10-28 14:42 UTC by kilatib

# [TR-4814](https://oat-sa.atlassian.net/browse/TR-4814)

## Description 
The title property of the item is shown in the item list and as the tooltip text.

## Development impact
just use right property as on other places

## Demo 
Unfortunately I cannot make up to run review mode on my local machine for proof, but for sure it is right fix

2022-10-28 14:51 UTC, poyuki approved these changes
nice)

2022-11-07 11:29 UTC, wazelin approved these changes

2022-11-07 14:10 UTC, wazelin approved these changes

2022-11-07 15:11 UTC, wazelin approved these changes
There we go again.

2022-11-07 15:12 UTC, wazelin requested changes
Oh, now that you touched a new php file, could you also fix its code style?

The CI pipeline requires it nowadays.

```
----------------------------------------------------------------------
FOUND 13 ERRORS AND 1 WARNING AFFECTING 12 LINES
----------------------------------------------------------------------
   1 | ERROR   | [x] Header blocks must be separated by a single
     |         |     blank line
  50 | ERROR   | [ ] The first trait import statement must be
     |         |     declared on the first non-comment line after the
     |         |     class opening brace
 131 | ERROR   | [x] Blank line found at start of control structure
 139 | ERROR   | [x] Opening parenthesis of a multi-line function
     |         |     call must be the last content on the line
 142 | ERROR   | [x] Multi-line function call not indented correctly;
     |         |     expected 16 spaces but found 20
 142 | ERROR   | [x] Only one argument is allowed per line in a
     |         |     multi-line function call
 142 | ERROR   | [x] Closing parenthesis of a multi-line function
     |         |     call must be on a line by itself
 207 | ERROR   | [x] Multi-line function call not indented correctly;
     |         |     expected 28 spaces but found 32
 208 | ERROR   | [x] Multi-line function call not indented correctly;
     |         |     expected 28 spaces but found 32
 209 | ERROR   | [x] Multi-line function call not indented correctly;
     |         |     expected 24 spaces but found 28
 255 | ERROR   | [x] There must not be a space before the colon in a
     |         |     return type declaration
 261 | WARNING | [ ] Line exceeds 120 characters; contains 139
     |         |     characters
 309 | ERROR   | [x] Expected 1 space(s) after closing parenthesis;
     |         |     found 2
 313 | ERROR   | [x] Expected 1 space after closing brace; newline
     |         |     found
```

2022-11-07 15:22 UTC, kilatib commented on models/QtiRunnerInitDataBuilder.php
> +                        'title' => $itemData['data']['attributes']['title'],
real change

2022-11-08 09:20 UTC, poyuki approved these changes

2022-11-08 10:34 UTC, wazelin approved these changes

2022-11-08 15:00 UTC, merged