feat: add brazilian portuguese language
oat-sa/extension-lti-test-review pull request #125
Opened 2023-04-25 13:42 UTC by albertosgz

Ticket: https://oat-sa.atlassian.net/browse/AUT-2995

## What has been done

Added brazilian portuguese and append `(Portugal)` to current portuguese.

![image](https://user-images.githubusercontent.com/12124175/234292920-f355e58f-6371-4983-97fd-1483359ec9a4.png)

### Requirements 

**Required** https://github.com/oat-sa/tao-core/pull/3791 to get new language option on select.

2023-04-29 07:57 UTC, bziondik approved these changes
No need to update composer dependencies - usually it is some features that implemented across extensions
No need to put bundles, they will be created on autorelease

- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on plauground (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2023-04-29 08:00 UTC, bziondik commented
CI fails maybe because of composer changes

2023-05-02 11:27 UTC, mike-ionut-mihai-sandu-tao commented
let's merge this PR please

2023-05-02 11:39 UTC, mike-ionut-mihai-sandu-tao requested changes

2023-05-02 11:39 UTC, mike-ionut-mihai-sandu-tao commented on composer.json
> +        "oat-sa/tao-core": "dev-feature/AUT-2995",
please revert

2023-05-04 14:21 UTC, merged