feat: added new endpoint for LTI1p3 review mode
oat-sa/extension-lti-test-review pull request #87
Opened 2021-09-21 13:34 UTC by emgolubev

Related to: https://oat-sa.atlassian.net/browse/TR-1910

Need to provide delivery execution id in custom claims.

Example for NG stack.

Launch URL: `http://backoffice.docker.localhost/ltiTestReview/ReviewTool/launch1p3`

```
{
    "https://purl.imsglobal.org/spec/lti/claim/roles": [
        "http://purl.imsglobal.org/vocab/lis/v2/membership#Learner"
    ],
    "https://purl.imsglobal.org/spec/lti/claim/custom": {
        "execution": "http://backoffice.docker.localhost/ontologies/tao.rdf#i6149ccf3252db7e59ff53bc7c1bcfc"
    }
}
```

DevKit Link

http://lti.docker.localhost/platform/message/launch/lti-resource-link?registration=devkitToTAO&user_list=c3po&launch_url=http://backoffice.docker.localhost/ltiTestReview/ReviewTool/launch1p3&claims=%7B%0D%0A%20%20%20%20%22https://purl.imsglobal.org/spec/lti/claim/roles%22:%20%5B%0D%0A%20%20%20%20%20%20%20%20%22http://purl.imsglobal.org/vocab/lis/v2/membership%23Learner%22%0D%0A%20%20%20%20%5D,%0D%0A%20%20%20%20%22https://purl.imsglobal.org/spec/lti/claim/custom%22:%20%7B%0D%0A%20%20%20%20%20%20%20%20%22execution%22:%20%22http://backoffice.docker.localhost/ontologies/tao.rdf%23i6149ccf3252db7e59ff53bc7c1bcfc%22%0D%0A%20%20%20%20%7D%0D%0A%7D

2021-09-21 13:34 UTC, emgolubev commented
Need to adjust a role who can launch a review mode

2021-09-21 16:05 UTC, alexeyvy approved these changes

2021-09-23 12:13 UTC, wazelin requested changes

2021-09-23 12:13 UTC, wazelin commented on controller/ReviewTool.php
> +        LtiService::singleton()->startLti1p3Session($message);
Please bump the taoLti extension version in `composer.json` dependencies, so that it points to the one, introducing that method.

2021-09-23 12:54 UTC, wazelin approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-09-24 14:34 UTC, merged